import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'
import NavbarSession from './components/navbar/NavbarSession'
import { Box } from '@chakra-ui/react'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en'>
      <body>
        <Providers>
          <Box bg='#f5f5ee' minH='100vh'>
            <NavbarSession />
            {children}
            <Footer />
          </Box>
        </Providers>
      </body>
    </html>
  )
}
